version: '3.3'

services:

  apples:
    image: caddy:2-alpine
    volumes:
      - ${PWD}/sources/docker-demo-apples/site/:/usr/share/caddy/:ro
      - caddy_data:/data

  banana:
    image: caddy:2-alpine
    volumes:
      - ${PWD}/sources/docker-demo-banana/site/:/usr/share/caddy/:ro
      - caddy_data:/data

  carrot:
    image: caddy:2-alpine
    volumes:
      - ${PWD}/sources/docker-demo-carrot/site/:/usr/share/caddy/:ro
      - caddy_data:/data

  proxy:
    image: caddy:2-alpine
    ports:
      - '80:80'
      - '443:443'
    depends-on:
      - apples
      - banana
      - carrot
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data

volumes:
  caddy_data:
    external: true
